version: '3'
services:
  movie_app:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "2222:8000"
    depends_on:
      - movie_data
  movie_data:
    image: 'postgres:14'
    environment:
      POSTGRES_DB: "movie_app_database"
      POSTGRES_USER: "user_python"
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - 'movie_data:/var/lib/postgresql/data'
volumes:
  movie_data: